name: tesk-api

on:
  push:
    branches: [ 'testing-gh-action' ]
    tags: [ '*' ]

  workflow_dispatch:
    inputs:
      profile:
        description: Profile name
        required: false
        default: tesk-api


jobs:
  build-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout elixir-cloud-aai/tesk-api
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: bash -c './mvnw clean verify'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            elixircloud/tesk-api:${{ github.GITHUB_REF_NAME }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

