name: GitHub Actions Build and Push Image on Tag

on:
  push:
    branches: [ 'testing-gh-action' ]
    tags: [ '*' ]

  workflow_dispatch:
    inputs:
      profile:
        description: Profile name
        required: false
        default: tesk-api

jobs:
  build-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout elixir-cloud-aai/tesk-api
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

